project:
  type: website
  resources:
    - /posts/webr/webr-serviceworker.js
    - /posts/webr/webr-worker.js
    - /posts/amino/coupons.json
    
website:
  title: "Agile Data Science"
  google-analytics: "G-M97VH8JRQ0"
  navbar:
    right:
      - author.qmd
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/maciej-nasinski/
      - icon: github
        text: Github
        href: https://github.com/polkas
format:
  html:
    css: styles.css
    search: true
    theme:
      light:
        - flatly
      dark:
        - darkly


