project:
  type: website
  resources:
    - /posts/webr/webr-serviceworker.js
    - /posts/webr/webr-worker.js
    - /logo.svg

website:
  title: "Agile Data Science"
  google-analytics: "G-M97VH8JRQ0"
  favicon: logo.svg
  navbar:
    right:
      - text: Posts
        href: posts.qmd
      - text: Author
        href: author.qmd
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/maciej-nasinski/
      - icon: github
        text: Github
        href: https://github.com/polkas
format:
  html:
    css: styles.css
    include-in-header:
      - text: |
          <meta http-equiv='cache-control' content='no-cache'> 
          <meta http-equiv='expires' content='0'> 
          <meta http-equiv='pragma' content='no-cache'>
    search: true
    theme:
      light:
        - flatly
      dark:
        - darkly
    lang: en-US
    page-layout: full
    toc: true
    webr:
      cell-options:
        autorun: true
        timelimit: 60
        max-lines: 30
    pyodide:
      cell-options:
        autorun: true
        max-lines: 30
    page-footer:
      left: |
        Made by polkas
    comments:
      giscus:
        # Reference: https://quarto.org/docs/reference/projects/books.html#giscus
        # Also https://giscus.app/ for all options
        repo: polkas/polkas.github.io
        category: General
        reactions-enabled: true
        theme: light
        language: en
        loading: lazy
        mapping: pathname

